name: Build Geode Mod

on:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Geode CLI
        run: |
          wget -q https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-linux.tar.gz
          tar -xzf geode-cli-linux.tar.gz
          chmod +x geode
          echo "$PWD" >> $GITHUB_PATH

      - name: Build Geode Mod
        run: geode build --config release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ROMImporterMod
          path: build/*.geode
