name: Build Geode Mod

on:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/action-install-geode-cli@main

      - name: Build Geode Mod
        run: geode build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ROMImporterMod
          path: build/*.geode
